spring:
  profiles:
    active: ${PROFILE:prod}

security:
  require-ssl: true

server:
  servlet:
    session:
      timeout=90m:
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: exampler-password
#    key-store-type: pkcs12
#    key-alias: exampler
#    key-password: exampler-password
  port: 8080

exampler:
  redirect-port: ${REDIRECT_PORT:8443}