spring:
  profiles:
    active: ${PROFILE:prod}

security:
  require-ssl: true

server:
  servlet:
    session:
      timeout=90m:
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: ifvfy
    key-store-type: pkcs12
    key-alias: exampler
    key-password: ifvfy
  port: 8443

exampler:
  redirect-port: ${REDIRECT_PORT:8443}