spring:
  profiles:
    active: ${PROFILE:prod}

security:
  require-ssl: true

server:
  servlet:
    session:
      timeout=90m:
  ssl:
    enabled: true
    key-store: classpath:keystore.properties
    key-store-type: PEMCFG
    key-store-password: dummy
    key-alias: keycert
  port: 8080

exampler:
  redirect-port: ${REDIRECT_PORT:8443}